language: java
sudo: false
notifications:
    on_success: change
    on_failure: change
os:
    - linux
#    - osx
jdk:
    - oraclejdk8
branches:
    only:
    - master
script:
    - make
    - tests/runtests.sh -s support/
