language: java
sudo: false
os:
    - linux
#    - osx
jdk:
    - oraclejdk8
branches:
    only:
    - master
script:
    - make
    - for x in tests/*; do if [ -d "$x" ]; then echo "Running through \"$x\""; tests/runtests.sh -t "$x" -s support; if [ $? -ne 0 ]; then test_success=false; fi; fi; done
    - exit $test_success
